pipeline {
    agent { label 'master-one' }   // Replace with your slave node label

    tools {
        jdk 'JDK21'
        maven 'Maven39'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('factorial-app') {         // <-- Add this
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('factorial-app') {         // <-- Add this
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('factorial-app') {         // <-- Add this
                    bat 'mvn package'
                }
            }
        }
    }
}
