pipeline {
    agent { label 'master-one' }   // Replace with your slave node label

    tools {
        maven 'Maven3'             // Name configured in Global Tool Configuration
        jdk 'JDK11'                // Optional (if configured)
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Package') {
            steps {
                bat 'mvn package'
            }
        }
    }
}
